// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypdazgppdjinxitkzlez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwZGF6Z3BwZGppbnhpdGt6bGV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODczNzksImV4cCI6MjA3NDY2MzM3OX0.tzXePB8eXMhDwJPWM7bWsX6jOeYyVI6S60-G1yXjnT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});